### ISSUE TITLE
Python脚本无法运行，麻烦博主帮忙看看。

### ISSUE THREAD

**Issue by lukbob** [xfgryujk/c51-play-music#1]
E:\tmp\c51-play-music\scripts>.\wav_to_pwm.py
  File "E:\tmp\c51-play-music\scripts\wav_to_pwm.py", line 54
    """)
      ^
SyntaxError: invalid syntax

------------------------------------------
试过python  2 ，3  都这样。搞不懂哪里有问题。
原来从博客复制的代码，以为有特殊字符。
追到这里，从github拿的代码，还是一样的错误。

**Comment by xfgryujk** [comment]
需要python 3.6以上版本
